name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  whitespace:
    name: Check whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check whitespace errors
        run: git diff-tree --check $(git hash-object -t tree /dev/null) HEAD

  style:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format
        run: make check-format

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Test
        run: make test